site_name: XCPC自学指北
site_url: https://mydomain.org/mysite
theme:
  name: material
  
  palette: # 调色板
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features: # 功能
    # - navigation.sections
    - navigation.tabs # 打开导航标签
    # - navigation.tabs.sticky # 启动粘性标签，当向下滚动的时候导航不会消失
    - navigation.top # 返回顶部按钮
    

    - content.code.copy # 代码复制按钮

    - navigation.footer # 页脚

markdown_extensions: # Markdown 扩展
  - pymdownx.arithmatex: # 数学公式
      generic: true

  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js # katex.js 数学公式
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css # katex.min.css 数学公式

nav:
  - 简介: index.md
  - 预学习:
    - 开始:
      - 课程 1-1 : A/1-introduce/lecture-1.md
      - 课程 1-2 : A/1-introduce/lecture-2.md
      - 课程 1-3 : A/1-introduce/lecture-3.md
    - HelloWorld:
      - 课程 2-1 : A/2-helloworld/lecture-1.md
      - 实验 2-1 : A/2-helloworld/lab-1.md
    - 运算符:
      - 课程 3-1 : A/3-a+b/lecture-1.md
      - 课程 3-2 : A/3-a+b/lecture-2.md
      - 实验 3-1 : A/3-a+b/lab-1.md
    - 条件语句:
      - 课程 4-1 : A/4-if/lecture-1.md
      - 实验 4-1 : A/4-if/lab-1.md
    - 循环语句:
      - 课程 5-1 : A/5-for/lecture-1.md
      - 实验 5-1 : A/5-for/lab-1.md
    - 数组:
      - 课程 6-1 : A/6-array/lecture-1.md
      - 实验 6-1 : A/6-array/lab-1.md
      - 课程 6-2 : A/6-array/lecture-2.md
      - 实验 6-2 : A/6-array/lab-2.md
    - 字符串:
      - 课程 7-1 : A/7-string/lecture-1.md
      - 实验 7-1 : A/7-string/lab-1.md
    - 函数:
      - 课程 8-1 : A/8-function/lecture-1.md
      - 实验 8-1 : A/8-function/lab-1.md
    - 递归:
      - 课程 9-1 : A/9-recursion/lecture-1.md
      - 实验 9-1 : A/9-recursion/lab-1.md
    - 模拟:
      - 课程 10-1 : A/10-simulation/lecture-1.md
      - 实验 10-1 : A/10-simulation/lab-1.md
  - 算法入门:
    - 动态规划:
      - Lecture 1 : B/dp/lecture-1.md
      - Lecture 2 : B/dp/lecture-2.md
      - Lab 2 : B/dp/lab-2.md
    - 图论:
      - Lecture 1 : B/graph/lecture-1.md
      - Lab 1 : B/graph/lab-1.md
      - Lecture 2 : B/graph/lecture-2.md
      - Lab 2 : B/graph/lab-2.md
      - Lecture 3 : B/graph/lecture-3.md
      - Lab 3 : B/graph/lab-3.md
      - Lecture 4 : B/graph/lecture-4.md
      - Lab 4 : B/graph/lab-4.md
      - Homework 1 : B/graph/homework-1.md
    - 字符串:
      - Lecture 1 : B/string/lecture-1.md
      - Lab 1 : B/string/lab-1.md
      - Homework 1 : B/string/homework-1.md
    - 对拍器:
      - Lecture 1 : B/check/lecture-1.md
      - Lab 1 : B/check/lab-1.md